name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 2.0.0-dev
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cryptography: ^2.7.0
  hive:
    git:
      url: https://github.com/pschaffl/hive.git
      path: hive
      ref: release
  path_provider: ^2.0.10
  path: ^1.8.1

dev_dependencies:
  test: ^1.21.1
  lints: ">=1.0.0"
  mockito: ^5.2.0
  build_runner: ^2.1.11
